version: '3'

services:
  node:
    image: sherryliao21/node-ramen-app:latest
    container_name: ramen-node-app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment: # will replace .env variables
      - MDB_HOST=mariadb:3306
      - MDB_USERNAME=root
      - MDB_PASSWORD=password
    networks:
      - ramen-network
    depends_on:
      - mariadb
    command: ['./wait-for-it.sh', 'mariadb:3308', '--', 'node', 'index.js']
    restart: always

  mariadb:
    image: mariadb:10.7.4
    container_name: ramen-mariaDB
    ports:
      - '3308:3306'
    environment:
      - MARIADB_ROOT_PASSWORD=password
    networks:
      - ramen-network
    volumes:
      - ramen-mariadb-data:/data/db

networks:
  ramen-network:
    driver: bridge

volumes:
  ramen-mariadb-data:
    driver: local
